// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"gu2list/ent/defautldb"
	"gu2list/ent/predicate"
	"gu2list/ent/users"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DefautlDBQuery is the builder for querying DefautlDB entities.
type DefautlDBQuery struct {
	config
	ctx           *QueryContext
	order         []defautldb.OrderOption
	inters        []Interceptor
	predicates    []predicate.DefautlDB
	withDefaultdb *UsersQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DefautlDBQuery builder.
func (ddq *DefautlDBQuery) Where(ps ...predicate.DefautlDB) *DefautlDBQuery {
	ddq.predicates = append(ddq.predicates, ps...)
	return ddq
}

// Limit the number of records to be returned by this query.
func (ddq *DefautlDBQuery) Limit(limit int) *DefautlDBQuery {
	ddq.ctx.Limit = &limit
	return ddq
}

// Offset to start from.
func (ddq *DefautlDBQuery) Offset(offset int) *DefautlDBQuery {
	ddq.ctx.Offset = &offset
	return ddq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddq *DefautlDBQuery) Unique(unique bool) *DefautlDBQuery {
	ddq.ctx.Unique = &unique
	return ddq
}

// Order specifies how the records should be ordered.
func (ddq *DefautlDBQuery) Order(o ...defautldb.OrderOption) *DefautlDBQuery {
	ddq.order = append(ddq.order, o...)
	return ddq
}

// QueryDefaultdb chains the current query on the "defaultdb" edge.
func (ddq *DefautlDBQuery) QueryDefaultdb() *UsersQuery {
	query := (&UsersClient{config: ddq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ddq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ddq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(defautldb.Table, defautldb.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, defautldb.DefaultdbTable, defautldb.DefaultdbPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(ddq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DefautlDB entity from the query.
// Returns a *NotFoundError when no DefautlDB was found.
func (ddq *DefautlDBQuery) First(ctx context.Context) (*DefautlDB, error) {
	nodes, err := ddq.Limit(1).All(setContextOp(ctx, ddq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{defautldb.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddq *DefautlDBQuery) FirstX(ctx context.Context) *DefautlDB {
	node, err := ddq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DefautlDB ID from the query.
// Returns a *NotFoundError when no DefautlDB ID was found.
func (ddq *DefautlDBQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddq.Limit(1).IDs(setContextOp(ctx, ddq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{defautldb.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddq *DefautlDBQuery) FirstIDX(ctx context.Context) int {
	id, err := ddq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DefautlDB entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DefautlDB entity is found.
// Returns a *NotFoundError when no DefautlDB entities are found.
func (ddq *DefautlDBQuery) Only(ctx context.Context) (*DefautlDB, error) {
	nodes, err := ddq.Limit(2).All(setContextOp(ctx, ddq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{defautldb.Label}
	default:
		return nil, &NotSingularError{defautldb.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddq *DefautlDBQuery) OnlyX(ctx context.Context) *DefautlDB {
	node, err := ddq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DefautlDB ID in the query.
// Returns a *NotSingularError when more than one DefautlDB ID is found.
// Returns a *NotFoundError when no entities are found.
func (ddq *DefautlDBQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddq.Limit(2).IDs(setContextOp(ctx, ddq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{defautldb.Label}
	default:
		err = &NotSingularError{defautldb.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddq *DefautlDBQuery) OnlyIDX(ctx context.Context) int {
	id, err := ddq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DefautlDBs.
func (ddq *DefautlDBQuery) All(ctx context.Context) ([]*DefautlDB, error) {
	ctx = setContextOp(ctx, ddq.ctx, "All")
	if err := ddq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DefautlDB, *DefautlDBQuery]()
	return withInterceptors[[]*DefautlDB](ctx, ddq, qr, ddq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ddq *DefautlDBQuery) AllX(ctx context.Context) []*DefautlDB {
	nodes, err := ddq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DefautlDB IDs.
func (ddq *DefautlDBQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ddq.ctx.Unique == nil && ddq.path != nil {
		ddq.Unique(true)
	}
	ctx = setContextOp(ctx, ddq.ctx, "IDs")
	if err = ddq.Select(defautldb.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddq *DefautlDBQuery) IDsX(ctx context.Context) []int {
	ids, err := ddq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddq *DefautlDBQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ddq.ctx, "Count")
	if err := ddq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ddq, querierCount[*DefautlDBQuery](), ddq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ddq *DefautlDBQuery) CountX(ctx context.Context) int {
	count, err := ddq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddq *DefautlDBQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ddq.ctx, "Exist")
	switch _, err := ddq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ddq *DefautlDBQuery) ExistX(ctx context.Context) bool {
	exist, err := ddq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DefautlDBQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddq *DefautlDBQuery) Clone() *DefautlDBQuery {
	if ddq == nil {
		return nil
	}
	return &DefautlDBQuery{
		config:        ddq.config,
		ctx:           ddq.ctx.Clone(),
		order:         append([]defautldb.OrderOption{}, ddq.order...),
		inters:        append([]Interceptor{}, ddq.inters...),
		predicates:    append([]predicate.DefautlDB{}, ddq.predicates...),
		withDefaultdb: ddq.withDefaultdb.Clone(),
		// clone intermediate query.
		sql:  ddq.sql.Clone(),
		path: ddq.path,
	}
}

// WithDefaultdb tells the query-builder to eager-load the nodes that are connected to
// the "defaultdb" edge. The optional arguments are used to configure the query builder of the edge.
func (ddq *DefautlDBQuery) WithDefaultdb(opts ...func(*UsersQuery)) *DefautlDBQuery {
	query := (&UsersClient{config: ddq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ddq.withDefaultdb = query
	return ddq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uint64 `json:"userID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DefautlDB.Query().
//		GroupBy(defautldb.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ddq *DefautlDBQuery) GroupBy(field string, fields ...string) *DefautlDBGroupBy {
	ddq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DefautlDBGroupBy{build: ddq}
	grbuild.flds = &ddq.ctx.Fields
	grbuild.label = defautldb.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uint64 `json:"userID,omitempty"`
//	}
//
//	client.DefautlDB.Query().
//		Select(defautldb.FieldUserID).
//		Scan(ctx, &v)
func (ddq *DefautlDBQuery) Select(fields ...string) *DefautlDBSelect {
	ddq.ctx.Fields = append(ddq.ctx.Fields, fields...)
	sbuild := &DefautlDBSelect{DefautlDBQuery: ddq}
	sbuild.label = defautldb.Label
	sbuild.flds, sbuild.scan = &ddq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DefautlDBSelect configured with the given aggregations.
func (ddq *DefautlDBQuery) Aggregate(fns ...AggregateFunc) *DefautlDBSelect {
	return ddq.Select().Aggregate(fns...)
}

func (ddq *DefautlDBQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ddq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ddq); err != nil {
				return err
			}
		}
	}
	for _, f := range ddq.ctx.Fields {
		if !defautldb.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddq.path != nil {
		prev, err := ddq.path(ctx)
		if err != nil {
			return err
		}
		ddq.sql = prev
	}
	return nil
}

func (ddq *DefautlDBQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DefautlDB, error) {
	var (
		nodes       = []*DefautlDB{}
		_spec       = ddq.querySpec()
		loadedTypes = [1]bool{
			ddq.withDefaultdb != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DefautlDB).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DefautlDB{config: ddq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ddq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ddq.withDefaultdb; query != nil {
		if err := ddq.loadDefaultdb(ctx, query, nodes,
			func(n *DefautlDB) { n.Edges.Defaultdb = []*Users{} },
			func(n *DefautlDB, e *Users) { n.Edges.Defaultdb = append(n.Edges.Defaultdb, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ddq *DefautlDBQuery) loadDefaultdb(ctx context.Context, query *UsersQuery, nodes []*DefautlDB, init func(*DefautlDB), assign func(*DefautlDB, *Users)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*DefautlDB)
	nids := make(map[int]map[*DefautlDB]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(defautldb.DefaultdbTable)
		s.Join(joinT).On(s.C(users.FieldID), joinT.C(defautldb.DefaultdbPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(defautldb.DefaultdbPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(defautldb.DefaultdbPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*DefautlDB]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Users](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "defaultdb" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (ddq *DefautlDBQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddq.querySpec()
	_spec.Node.Columns = ddq.ctx.Fields
	if len(ddq.ctx.Fields) > 0 {
		_spec.Unique = ddq.ctx.Unique != nil && *ddq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ddq.driver, _spec)
}

func (ddq *DefautlDBQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(defautldb.Table, defautldb.Columns, sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt))
	_spec.From = ddq.sql
	if unique := ddq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ddq.path != nil {
		_spec.Unique = true
	}
	if fields := ddq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, defautldb.FieldID)
		for i := range fields {
			if fields[i] != defautldb.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddq *DefautlDBQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddq.driver.Dialect())
	t1 := builder.Table(defautldb.Table)
	columns := ddq.ctx.Fields
	if len(columns) == 0 {
		columns = defautldb.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddq.sql != nil {
		selector = ddq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddq.ctx.Unique != nil && *ddq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ddq.predicates {
		p(selector)
	}
	for _, p := range ddq.order {
		p(selector)
	}
	if offset := ddq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DefautlDBGroupBy is the group-by builder for DefautlDB entities.
type DefautlDBGroupBy struct {
	selector
	build *DefautlDBQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddgb *DefautlDBGroupBy) Aggregate(fns ...AggregateFunc) *DefautlDBGroupBy {
	ddgb.fns = append(ddgb.fns, fns...)
	return ddgb
}

// Scan applies the selector query and scans the result into the given value.
func (ddgb *DefautlDBGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ddgb.build.ctx, "GroupBy")
	if err := ddgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DefautlDBQuery, *DefautlDBGroupBy](ctx, ddgb.build, ddgb, ddgb.build.inters, v)
}

func (ddgb *DefautlDBGroupBy) sqlScan(ctx context.Context, root *DefautlDBQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ddgb.fns))
	for _, fn := range ddgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ddgb.flds)+len(ddgb.fns))
		for _, f := range *ddgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ddgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DefautlDBSelect is the builder for selecting fields of DefautlDB entities.
type DefautlDBSelect struct {
	*DefautlDBQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dds *DefautlDBSelect) Aggregate(fns ...AggregateFunc) *DefautlDBSelect {
	dds.fns = append(dds.fns, fns...)
	return dds
}

// Scan applies the selector query and scans the result into the given value.
func (dds *DefautlDBSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dds.ctx, "Select")
	if err := dds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DefautlDBQuery, *DefautlDBSelect](ctx, dds.DefautlDBQuery, dds, dds.inters, v)
}

func (dds *DefautlDBSelect) sqlScan(ctx context.Context, root *DefautlDBQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dds.fns))
	for _, fn := range dds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
