// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gu2list/ent/defautldb"
	"gu2list/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DefautlDBDelete is the builder for deleting a DefautlDB entity.
type DefautlDBDelete struct {
	config
	hooks    []Hook
	mutation *DefautlDBMutation
}

// Where appends a list predicates to the DefautlDBDelete builder.
func (ddd *DefautlDBDelete) Where(ps ...predicate.DefautlDB) *DefautlDBDelete {
	ddd.mutation.Where(ps...)
	return ddd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ddd *DefautlDBDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ddd.sqlExec, ddd.mutation, ddd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ddd *DefautlDBDelete) ExecX(ctx context.Context) int {
	n, err := ddd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ddd *DefautlDBDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(defautldb.Table, sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt))
	if ps := ddd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ddd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ddd.mutation.done = true
	return affected, err
}

// DefautlDBDeleteOne is the builder for deleting a single DefautlDB entity.
type DefautlDBDeleteOne struct {
	ddd *DefautlDBDelete
}

// Where appends a list predicates to the DefautlDBDelete builder.
func (dddo *DefautlDBDeleteOne) Where(ps ...predicate.DefautlDB) *DefautlDBDeleteOne {
	dddo.ddd.mutation.Where(ps...)
	return dddo
}

// Exec executes the deletion query.
func (dddo *DefautlDBDeleteOne) Exec(ctx context.Context) error {
	n, err := dddo.ddd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{defautldb.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dddo *DefautlDBDeleteOne) ExecX(ctx context.Context) {
	if err := dddo.Exec(ctx); err != nil {
		panic(err)
	}
}
