// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gu2list/ent/defautldb"
	"gu2list/ent/schema"
	"gu2list/ent/users"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	defautldbFields := schema.DefautlDB{}.Fields()
	_ = defautldbFields
	// defautldbDescAccept is the schema descriptor for accept field.
	defautldbDescAccept := defautldbFields[2].Descriptor()
	// defautldb.DefaultAccept holds the default value on creation for the accept field.
	defautldb.DefaultAccept = defautldbDescAccept.Default.(bool)
	// defautldbDescTimeAt is the schema descriptor for timeAt field.
	defautldbDescTimeAt := defautldbFields[3].Descriptor()
	// defautldb.DefaultTimeAt holds the default value on creation for the timeAt field.
	defautldb.DefaultTimeAt = defautldbDescTimeAt.Default.(int64)
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescManager is the schema descriptor for Manager field.
	usersDescManager := usersFields[2].Descriptor()
	// users.DefaultManager holds the default value on creation for the Manager field.
	users.DefaultManager = usersDescManager.Default.(bool)
}
