// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gu2list/ent/defautldb"
	"gu2list/ent/predicate"
	"gu2list/ent/schema"
	"gu2list/ent/users"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersUpdate is the builder for updating Users entities.
type UsersUpdate struct {
	config
	hooks    []Hook
	mutation *UsersMutation
}

// Where appends a list predicates to the UsersUpdate builder.
func (uu *UsersUpdate) Where(ps ...predicate.Users) *UsersUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUserID sets the "userID" field.
func (uu *UsersUpdate) SetUserID(u uint64) *UsersUpdate {
	uu.mutation.ResetUserID()
	uu.mutation.SetUserID(u)
	return uu
}

// AddUserID adds u to the "userID" field.
func (uu *UsersUpdate) AddUserID(u int64) *UsersUpdate {
	uu.mutation.AddUserID(u)
	return uu
}

// SetRoles sets the "roles" field.
func (uu *UsersUpdate) SetRoles(s *schema.Roles) *UsersUpdate {
	uu.mutation.SetRoles(s)
	return uu
}

// SetManager sets the "Manager" field.
func (uu *UsersUpdate) SetManager(b bool) *UsersUpdate {
	uu.mutation.SetManager(b)
	return uu
}

// SetNillableManager sets the "Manager" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableManager(b *bool) *UsersUpdate {
	if b != nil {
		uu.SetManager(*b)
	}
	return uu
}

// SetUpdateAt sets the "updateAt" field.
func (uu *UsersUpdate) SetUpdateAt(i int64) *UsersUpdate {
	uu.mutation.ResetUpdateAt()
	uu.mutation.SetUpdateAt(i)
	return uu
}

// AddUpdateAt adds i to the "updateAt" field.
func (uu *UsersUpdate) AddUpdateAt(i int64) *UsersUpdate {
	uu.mutation.AddUpdateAt(i)
	return uu
}

// AddLogIDs adds the "logs" edge to the DefautlDB entity by IDs.
func (uu *UsersUpdate) AddLogIDs(ids ...int) *UsersUpdate {
	uu.mutation.AddLogIDs(ids...)
	return uu
}

// AddLogs adds the "logs" edges to the DefautlDB entity.
func (uu *UsersUpdate) AddLogs(d ...*DefautlDB) *UsersUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uu.AddLogIDs(ids...)
}

// Mutation returns the UsersMutation object of the builder.
func (uu *UsersUpdate) Mutation() *UsersMutation {
	return uu.mutation
}

// ClearLogs clears all "logs" edges to the DefautlDB entity.
func (uu *UsersUpdate) ClearLogs() *UsersUpdate {
	uu.mutation.ClearLogs()
	return uu
}

// RemoveLogIDs removes the "logs" edge to DefautlDB entities by IDs.
func (uu *UsersUpdate) RemoveLogIDs(ids ...int) *UsersUpdate {
	uu.mutation.RemoveLogIDs(ids...)
	return uu
}

// RemoveLogs removes "logs" edges to DefautlDB entities.
func (uu *UsersUpdate) RemoveLogs(d ...*DefautlDB) *UsersUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uu.RemoveLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UsersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UsersUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UsersUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UsersUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UsersUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(users.Table, users.Columns, sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.UserID(); ok {
		_spec.SetField(users.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := uu.mutation.AddedUserID(); ok {
		_spec.AddField(users.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := uu.mutation.Roles(); ok {
		_spec.SetField(users.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.Manager(); ok {
		_spec.SetField(users.FieldManager, field.TypeBool, value)
	}
	if value, ok := uu.mutation.UpdateAt(); ok {
		_spec.SetField(users.FieldUpdateAt, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedUpdateAt(); ok {
		_spec.AddField(users.FieldUpdateAt, field.TypeInt64, value)
	}
	if uu.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.LogsTable,
			Columns: users.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedLogsIDs(); len(nodes) > 0 && !uu.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.LogsTable,
			Columns: users.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.LogsTable,
			Columns: users.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UsersUpdateOne is the builder for updating a single Users entity.
type UsersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsersMutation
}

// SetUserID sets the "userID" field.
func (uuo *UsersUpdateOne) SetUserID(u uint64) *UsersUpdateOne {
	uuo.mutation.ResetUserID()
	uuo.mutation.SetUserID(u)
	return uuo
}

// AddUserID adds u to the "userID" field.
func (uuo *UsersUpdateOne) AddUserID(u int64) *UsersUpdateOne {
	uuo.mutation.AddUserID(u)
	return uuo
}

// SetRoles sets the "roles" field.
func (uuo *UsersUpdateOne) SetRoles(s *schema.Roles) *UsersUpdateOne {
	uuo.mutation.SetRoles(s)
	return uuo
}

// SetManager sets the "Manager" field.
func (uuo *UsersUpdateOne) SetManager(b bool) *UsersUpdateOne {
	uuo.mutation.SetManager(b)
	return uuo
}

// SetNillableManager sets the "Manager" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableManager(b *bool) *UsersUpdateOne {
	if b != nil {
		uuo.SetManager(*b)
	}
	return uuo
}

// SetUpdateAt sets the "updateAt" field.
func (uuo *UsersUpdateOne) SetUpdateAt(i int64) *UsersUpdateOne {
	uuo.mutation.ResetUpdateAt()
	uuo.mutation.SetUpdateAt(i)
	return uuo
}

// AddUpdateAt adds i to the "updateAt" field.
func (uuo *UsersUpdateOne) AddUpdateAt(i int64) *UsersUpdateOne {
	uuo.mutation.AddUpdateAt(i)
	return uuo
}

// AddLogIDs adds the "logs" edge to the DefautlDB entity by IDs.
func (uuo *UsersUpdateOne) AddLogIDs(ids ...int) *UsersUpdateOne {
	uuo.mutation.AddLogIDs(ids...)
	return uuo
}

// AddLogs adds the "logs" edges to the DefautlDB entity.
func (uuo *UsersUpdateOne) AddLogs(d ...*DefautlDB) *UsersUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uuo.AddLogIDs(ids...)
}

// Mutation returns the UsersMutation object of the builder.
func (uuo *UsersUpdateOne) Mutation() *UsersMutation {
	return uuo.mutation
}

// ClearLogs clears all "logs" edges to the DefautlDB entity.
func (uuo *UsersUpdateOne) ClearLogs() *UsersUpdateOne {
	uuo.mutation.ClearLogs()
	return uuo
}

// RemoveLogIDs removes the "logs" edge to DefautlDB entities by IDs.
func (uuo *UsersUpdateOne) RemoveLogIDs(ids ...int) *UsersUpdateOne {
	uuo.mutation.RemoveLogIDs(ids...)
	return uuo
}

// RemoveLogs removes "logs" edges to DefautlDB entities.
func (uuo *UsersUpdateOne) RemoveLogs(d ...*DefautlDB) *UsersUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uuo.RemoveLogIDs(ids...)
}

// Where appends a list predicates to the UsersUpdate builder.
func (uuo *UsersUpdateOne) Where(ps ...predicate.Users) *UsersUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UsersUpdateOne) Select(field string, fields ...string) *UsersUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated Users entity.
func (uuo *UsersUpdateOne) Save(ctx context.Context) (*Users, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UsersUpdateOne) SaveX(ctx context.Context) *Users {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UsersUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UsersUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UsersUpdateOne) sqlSave(ctx context.Context) (_node *Users, err error) {
	_spec := sqlgraph.NewUpdateSpec(users.Table, users.Columns, sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Users.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, users.FieldID)
		for _, f := range fields {
			if !users.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != users.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.UserID(); ok {
		_spec.SetField(users.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := uuo.mutation.AddedUserID(); ok {
		_spec.AddField(users.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := uuo.mutation.Roles(); ok {
		_spec.SetField(users.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.Manager(); ok {
		_spec.SetField(users.FieldManager, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.UpdateAt(); ok {
		_spec.SetField(users.FieldUpdateAt, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedUpdateAt(); ok {
		_spec.AddField(users.FieldUpdateAt, field.TypeInt64, value)
	}
	if uuo.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.LogsTable,
			Columns: users.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedLogsIDs(); len(nodes) > 0 && !uuo.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.LogsTable,
			Columns: users.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.LogsTable,
			Columns: users.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defautldb.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Users{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
